### ISSUE TITLE
[Guide]: 개발환경 구성을 위해 미리 설치되어 있어야 할 프로그램

### ISSUE THREAD

**Issue by yongoh** [eGovFramework/egovframe-msa-edu#15]
### 개발가이드 URL Dev Guide URL

https://github.com/eGovFramework/egovframe-msa-edu#readme, https://github.com/eGovFramework/egovframe-msa-edu/files/11084632/03.MSA._.pdf

### 수정 대상 내용 What to fix

개발환경 구성을 위해 설치되어 있어야 할 프로그램들(Erlang/OTP, RabbitMQ, Swagger 등)에 대한 안내가 
readme 파일과, 
02.MSA템플릿 백엔드구성 및 실습.pdf 문서 등에 
안내되어 있으면 좋을것 같습니다.

### 수정 문구 Corrective Wording

[프로잭트 구성전 설치해야 할 프로그램]
Erlang/OTP 다운로드/설치 : https://www.erlang.org/downloads
RabbitMQ 다운로드/설치 : https://www.rabbitmq.com/download.html

**Comment by eGovFrameSupport** [comment]
[2023 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'23년 4월 10일부터 8월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2023 전자정부 표준프레임워크 컨트리뷰션"을 실시 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.

https://forms.gle/g5cKfG5rnNrqvqjaA

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 감사장과 표준프레임워크 오픈커뮤니티에서 소정의 기념품을 택배 배송 해 드립니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by overpassion** [comment]
감사합니다.
