### ISSUE TITLE
[발전 방안 제안(Improvement Plan)]: MSA 확산을 위한 Gateway 기본 기능 강화

### ISSUE THREAD

**Issue by yunkid** [eGovFramework/egovframe-msa-edu#21]
### 아이디어명 Idea Name

API Gateway Admin-UI 및 공통 컴포넌트 구성 추가

### 아이디어 요약 Idea Summary
Spring Cloud Gateway (이하 SCG로 표기)가 제공하는 Route,Filter 등의 API와, Spring Integration을 같이 통합 구성하여 MSA 구축 또는 전환 시 전자정부 프레임워크를 통해 확장성과 활용성을 높일 수 있도록 제안하는 아이디어 입니다.

1. Redis와 Cloud Gateway 에서 제공하는 API를 이용하여 활용성과 확장성을 높이기 위한 공통 서비스(라우팅 설정, 다이나믹 라우팅, 다양한 프로토콜 지원) 추가 및 이를 쉽게 활용할 수 있는 Admin UI 추가 

2. SCG의 경우 REST API 중심으로 TCP 나 UDP는 지원하지 않고 있음, Spring Integration 모듈을 추가하여 TCP,UDP도 지원 가능 하도록 아키텍처 구성 및 공통 모듈 추가.

※ Spring Integration은 UI구성이 어려울 수 있으므로, Admin UI는 SCG 관리를 위한 인터페이스만 제공하고, Spring Integration은 공통 컴포넌트 식으로 추가

### 제안배경 Suggestion Background

[클라우드 네이티브 기술 도입에 대한 Risk]
Spring Cloud를 통한 클라우드 네이티브 아키텍처 도입 시 API Gateway (Spring Cloud Gateway)의 커스터마이징 및 구성에 적지 않은 시간이 소요되고 있으며, TCP 소켓 방식 등 다양한 프로토콜 지원을 위한 표준화 된 라이브러리가 없는 상태로 기술 적용에 대한 어려움과 RISK가 많은 상태 입니다.

[프로젝트 진행 시 한정된 기간 내 구성의 어려움]
SCG 라우팅 및 필터 설정은 YML 이나 직접 Config으로 설정하도록 되어 있어 무중단 서비스를 위한 다이나믹 서비스 구축 시
초기 단계에서 표준을 잡거나 활용 방안을 기획함에 있어 번번한 시행 착오가 발생 할 수 있습니다.
또한 특정 섹터의 경우 REST API 뿐만이 아닌 TCP 등의 별도 프로토콜을 이용해야 하는 경우가 있는데 매번 새롭게 
구성을 해야 하는 어려움이 있습니다.

[상기 Risk와 구성의 어려움 해결을 위한 극복 방안]
SCG에서 제공하는 Admin API를 활용하여 라우터 설정이나 필터등의 설정을 할 수 있는 모듈을 추가하고,
이를 기본적으로 관리할 수 있도록 하는 Amdin UI를 구성하여 좀 더 쉽게 적용 및 프레임워크 구성이 가능하도록 제안을 드립니다.

Spring Cloud의 경우 마치 Oauth와 유사하게 표준화 된 정책은 없지만, 활용하기에 따라 다양하게 구성할 수 있는
장점이 있으나 기간이 한정되어 있는 SI프로젝트에서는 이는 단점이 될 수 있으며 API 서비스 구성과 API Management측면에서 매번 고민이 되는 부분으로 API Gateway에서 가장 많이 사용하게 될 라우터, 필터 우선으로 레디스에 설정을 저장하고
 이를 UI를 통해 세팅 및 활용 할 수 있는 Admin UI 추가가 필요해 보이며 구성이 된다면 현장에 매우 큰 도움이 될 것으로 보입니다.

[예시] (참고문헌1)  /gateway/routes SCG API를 이용하여 json 구조로 설정을 dynamic 하게 저장,수정,관리, 적용이 가능.(Admin API 관리 화면에서는 route와 필터를 key-value형식으로 입력받아 json으로 저장하고 이를 route에 반영)

또한 별도 프로젝트로 되어 있는 Spring Integration 공통 모듈을 포함하여 TCP,UDP등 다양한 프로토콜을 지원 가능하도록 하여 확장성을 높이면 다양한 섹터에서의 활용성이 증대될 것으로 보입니다.

### 기대효과 Expectations

1. SI프로젝트를 통한 MSA 또는 미니서비스 전환 시 매우 유용하고 진입 장벽을 낮출 수 있음
2. 프로젝트 초기 단계에서 파일럿 진행 시 개발/테스트를 빠르게 적용할 수 있음 
4. 잘 구성된 Admin UI가 있다면 전세계적으로도 공유하여 확산 및 활용 고도화가 가능
   (현재 SCG의 활용가능 할만한 오픈소스 Admin-UI는 없는 것으로 보이며, 잘 구성이 될 경우 글로벌 컨트리뷰터 참여 유도 가능)
5. REST API 외에 TCP, UDP 등 다양한 프로토콜 지원을 통해 핵심 비지니스 구현에만 집중이 가능하도록 하여 품질을 높이고 구축 기간 단축

### 자유기술 Free Writing
- 도커에서 바로 가져다 쓸 수 있도록 이미지가 제공되면 좋을 듯 합니다.(도커 허브 등록 또는 스크립트 제공)
- 미니 쿠버네티스 환경 구성을 위한 샘플도 제공이 되면 많은 도움이 될 것으로 보입니다.

### 참고문헌 Reference
**1. Dynamic Configuration of Spring Cloud Gateway Routing**
    https://blog.nashtechglobal.com/dynamic-conf-spring-cloud-gateway-routing/
**2. Spring Cloud Gateway — Dynamic Route Configuration and Loading from the Datastore**
    https://anjireddy-kata.medium.com/spring-cloud-gateway-dynamic-route-configuration-and-loading-from-the-datastore-a0637e6bd9b4
**3. Spring Cloud Gateway Actuator API**
   https://docs.spring.io/spring-cloud-gateway/reference/spring-cloud-gateway/actuator-api.html

**Comment by eGovFrameSupport** [comment]
안녕하세요
전자정부 표준프레임워크 센터입니다.

'24년 7월 29일부터 9월 30일까지 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2024년 전자정부 표준프레임워크 컨트리뷰션"을 개최 하였습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며,  전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다. 
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.

앞으로도 전자정부 표준프레임워크에 지속적인 관심 바라오며, 아래 URL 접속, 설문지로 이동하여 항목에 응답 부탁드립니다.
https://forms.gle/6qRXGFZn5WTaxBCK8

※ 컨트리뷰션 종료 후, 시상관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by overpassion** [comment]
표준프레임워크에 대한 관심과 
정성어린 이슈제안에 감사드립니다.
