### ISSUE TITLE
* VS Code를 이용한 편집

### ISSUE THREAD

**Issue by likiwook** [eGovFramework/egovframe-msa-edu#27]
### 아이디어명 Idea Name

VS Code를 이용한 편집

### 아이디어 요약 Idea Summary

VS Code를 이용한 편집

### 제안배경 Suggestion Background

VS Code를 이용한 편집 시 가성비 높음

### 자유기술 Free Writing

VS Code를 이용한 편집 시 가성비 높음

### 참고문헌 Reference

VS Code를 이용한 편집 시 가성비 높음

**Comment by overpassion** [comment]
감사합니다.
Github에서 codespace 사용시 VSCode 기반으로 사용이 가능한점 참고 부탁드립니다.
