### ISSUE TITLE
프로젝트에 대한 튜토리얼 같은 설명과 문서가 필요해 보입니다

### ISSUE THREAD

**Issue by youngick** [eGovFramework/egovframe-msa-edu#3]
해당 프로젝트에 대한 설명과 문서가 너무 없어서 아쉽네요.
도커나 쿠버네티스 초보자들도 따라하면서 공부 할 수 있도록 설명과 그림이 추가 되면 좋겠습니다.
제가 직접 하나씩 해보면서 설명과 그림을 작성해보려 했지만, 
애시당초 설명이 거의 없어서 어떻게 시작해야 할지도 막막하더군요.

검색을 해보니 커뮤니티 자료실에서 PDF 문서를 찾았습니다.
일단은 이 문서 링크라도 걸어주시면 좋겠습니다.
[https://open.egovframe.org/oc/docs/pdsItem.do?nttId=20023](https://open.egovframe.org/oc/docs/pdsItem.do?nttId=20023)

유튜브에서 관련 영상들도 찾았습니다.
[https://www.youtube.com/channel/UC_ZpWtFSV_e_Y5iWjPsGbxQ/search?query=MSA](https://www.youtube.com/channel/UC_ZpWtFSV_e_Y5iWjPsGbxQ/search?query=MSA)

**Comment by eGovFrameSupport** [comment]
[2022 전자정부 표준프레임워크 컨트리뷰션 참가 기념품 발송안내]

안녕하세요
전자정부 표준프레임워크 센터입니다.

'22년 3월 28일부터 7월 31일까지 약 4개월간, 전자정부 서비스 개발 표준 기반인 "전자정부 표준프레임워크" 개선에 민간 SW개발자의 아이디어와 의견을 반영하기 위해 "2022 전자정부 표준프레임워크 컨트리뷰션"을 실시하고 있습니다.

표준프레임워크 깃허브(github.com/egovframework)에 보내주신 귀하의 의견에 감사드리며, 전자정부 표준프레임워크 운영·개선 과정에서 유용하게 활용토록 하겠습니다.
본 설문에 응답 주시면 표준프레임워크에서 마련한 소정의 기념품을 발송 드릴 예정이오니, 문항에 빠짐없이 응답 해 주시기 바랍니다.
아래의 URL을 통하여 설문지로 이동, 항목에 응답 부탁드립니다.
http://forms.gle/nWPW3cpnUs3Azjur5

앞으로도 전자정부 표준프레임워크에 지속적인 관심 부탁드립니다.

※ 센터에서 준비한 소정의 기념품과 함께 표준프레임워크 오픈커뮤니티에서 커피쿠폰을 같이 발송 드릴 예정입니다.
※ 컨트리뷰션 종료 후, 시상 관련하여 연락 갈 예정이오니, 꼭 통화 가능한 본인번호를 기재해 주시기 바랍니다.
※ 귀하께서 답변해 주시는 내용은 컨트리뷰션 참가 확인 및 기념품 발송 목적으로만 활용되며, 개인정보는 기념품 발송 후 즉시 영구 삭제처리 됩니다.

감사합니다.

**Comment by chris-yoon** [comment]
참여해 주셔서 감사드립니다.
