### ISSUE TITLE
[발전 방안 제안(Improvement Plan)]: Service Discovery Server 복수 서버 구성 방안 검토

### ISSUE THREAD

**Issue by y0unghwanhwang** [eGovFramework/egovframe-msa-edu#32]
### 아이디어명 Idea Name

Service Discovery Server 복수 서버 구성 방안 검토

### 아이디어 요약 Idea Summary

현재 단일 서버로 구성된 Service Discovery Server(Eureka Server)의 단일 장애 지점(SPOF) 문제를 해결하기 위한 방안을 제안드립니다. 

Eureka Server를 복수 개의 서버로 구성하여 클러스터를 구축함으로써:
1. 각 Eureka Server는 서로의 상태를 복제하고 동기화
2. 한 서버에 장애가 발생해도 다른 서버가 서비스를 계속 제공
3. 서버 간 데이터 동기화를 통한 서비스 등록 정보의 안정성 확보
4. 부하 분산을 통한 시스템 안정성 향상

이를 통해 실제 운영 환경에서 발생할 수 있는 다양한 장애 상황에 대응할 수 있는 고가용성 아키텍처를 구성하고자 합니다.

### 제안배경 Suggestion Background

마이크로서비스 아키텍처에서 Service Discovery는 각 서비스의 위치를 찾고 통신할 수 있게 하는 핵심 컴포넌트입니다. 현재 프로젝트에서는 이 역할을 하는 Eureka Server가 단일 서버로 구성되어 있습니다. 만약 이 서버에 장애가 발생한다면, 새로운 서비스 등록이 불가능해지고 이미 등록된 서비스의 위치 정보를 찾을 수 없게 되어 전체 시스템에 심각한 영향을 미칠 수 있습니다. 특히 동적으로 서비스가 추가되고 제거되는 클라우드 환경에서는 이러한 문제가 더욱 치명적일 수 있습니다. 따라서 서비스 디스커버리 서버의 가용성을 높이고 안정적인 서비스 운영을 위해서는 복수 서버 구성이 필요하다고 생각합니다.

### 기대효과 Expectations

1. 서비스 안정성 강화
  - 단일 장애 지점 제거를 통한 시스템 신뢰성 향상
  - 서버 간 복제를 통한 데이터 안정성 확보
  - 장애 상황에서도 지속적인 서비스 제공 가능

2. 실제 운영 환경 수준의 아키텍처 경험
  - 운영 환경에서 필수적인 고가용성 구성 방식 학습
  - 실제 클라우드 환경과 유사한 구성으로 실무 역량 강화
  - 서버 클러스터 운영 및 관리 경험 습득

3. 마이크로서비스 심화 학습
  - 서비스 디스커버리의 고가용성 구성 원리 이해
  - 클러스터 환경에서의 서비스 등록/발견 메커니즘 학습
  - 분산 시스템의 데이터 동기화 개념 습득

### 자유기술 Free Writing

[문의 사항]
1. 현재 단일 Eureka Server 구성이 교육 목적을 위한 의도적인 설계인지 궁금합니다.
2. 만약 개선이 필요하다고 판단되신다면, 제가 직접 Eureka Server 클러스터 구성을 위한 PR을 제안드려도 될지 문의 드립니다.

### 참고문헌 Reference

1. Service Discovery Pattern: https://microservices.io/tags/service%20discovery
2. Single Point of Failure (SPOF): https://en.wikipedia.org/wiki/Single_point_of_failure

**Comment by overpassion** [comment]
안녕하세요.
답변1) 현 레포지토리는 교육목적 및 개발착수시 참고용으로 배포하고 있습니다. 따라서 부족한 기능이 있을수 있습니다. 필요한 경우 확장하여 적용하실수 있습니다.
답변2) 기능 확장을 위한 PR은 언제든 환영합니다. 다만, 추가된 기능에 대한 기본적인 테스트를 하신후 PR을 부탁드립니다.
감사합니다. ^^
