### ISSUE TITLE
[Bug]: frontend admin 및 portal 패키지 의존성 및 빌드 문제

### ISSUE THREAD

**Issue by parandiary** [eGovFramework/egovframe-msa-edu#33]
### 연락처 Contact

parandiary@gmail.com

### 오류 내용 Error Description

npm install 및 실행에 문제가 있습니다.

![image](https://github.com/user-attachments/assets/429c57f2-95e5-4066-98bc-9ea92881aaaf)
![image](https://github.com/user-attachments/assets/84d7ad45-a750-4afa-9c94-3c94087aa778)

### 오류 재현 방법 How to reproduce the error

(다음은 예시이며, 내용을 덮어 써 주세요. The following is an example, please overwrite the content.)

 1. 다음 메뉴를 선택한다. Select the following menu '...'
 2. 다음 버튼을 클릭한다. Click the Next button. '....'
 3. 다음 문구까지 스크롤 다운한다. Scroll down to the following phrase '....'
 4. 오류를 확인한다. Check for errors.

### 환경정보 Environmental Information

 - OS정보 : windows
 - 표준프레임워크 버전 eGovFrame Version: 4.2
 - JDK(JRE) 정보: 
 - WAS 정보: 
 - DB 정보: 
 - 기타 환경 정보 Other environmental information:

### 어느 브라우저를 사용했나요? Which browser did you use?

Chrome

### 에러 로그 Error Logs

```shell
(base) PS D:\DEV\workspaces\workspace-egov\egovframe-msa-edu\frontend\portal> npm run dev

> msa-template-portal@0.1.0 dev D:\DEV\workspaces\workspace-egov\egovframe-msa-edu\frontend\portal
> ts-node --transpile-only --project tsconfig.server.json server/index.ts

Loaded env from .env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
It looks like you're trying to use TypeScript but do not have the required package(s) installed.

Please install @types/react by running:

        yarn add --dev @types/react

If you are not trying to use TypeScript, please remove the tsconfig.json file from your package root (and any TypeScript files in your pages directory).

npm ERR! errno 1
npm ERR! msa-template-portal@0.1.0 dev: `ts-node --transpile-only --project tsconfig.server.json server/index.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the msa-template-portal@0.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2024-11-04T01_20_05_651Z-debug.log
(base) PS D:\DEV\workspaces\workspace-egov\egovframe-msa-edu\frontend\portal>
(base) PS D:\DEV\workspaces\workspace-egov\egovframe-msa-edu\frontend\portal> nvm ls

    20.18.0
    18.20.4
    16.20.2
    14.21.3
  * 14.8.0 (Currently using 64-bit executable)
(base) PS D:\DEV\workspaces\workspace-egov\egovframe-msa-edu\frontend\portal> npm -v
6.14.7
(base) PS D:\DEV\workspaces\workspace-egov\egovframe-msa-edu\frontend\portal>
```

**Comment by overpassion** [comment]
Windows OS 11
Node v14.21.3
NPM v6.14.18
위 환경에서 확인 하였을 때 정상적으로 구동이 되었습니다.
해당 디렉토리를 삭제 또는 백업하신후
git clone https://github.com/eGovFramework/egovframe-msa-edu
한 다음 다음 명령을 실행해 보시기 바랍니다.
npm install 
npm run dev:lgWin
