### ISSUE TITLE
mui 및 next js 최신버전 갱신이 필요해 보입니다.

### ISSUE THREAD

**Issue by nadeda** [eGovFramework/egovframe-msa-edu#4]
mui 및 next js 13버전 갱신이 필요해 보입니다.

**Comment by overpassion** [comment]
소중한 의견 감사합니다. 향후 수요등을 고려하여 우선순위에 따라 차후에 진행되어야 할것으로 보입니다.

**Comment by nadeda** [comment]
감사합니다.
msa-edu 프로젝트로 올라와져 있는데 egovframework 4.1에서 제공되는 버전이 여기 레파지토리 버전인가요? 아니면 따로 레파지토리를 관리하고 있는 걸까요?

**Comment by overpassion** [comment]
govframe-msa-edu는 21년 말에 배포되었는데요. 
표준프레임워크 실행환경은 egovframe-runtime ,
개발환경은 egovframe-development
공통컴포넌트는 egovframe-common-components 입니다.
여기 배포된 버전은 4.0이고 
v4.1은 표준프레임워크 포탈사이트에만 베타 버전으로 배포 되어 있습니다.
곧 여기 GitHub에도 배포될 예정입니다.

**Comment by chris-yoon** [comment]
참여해 주셔서 감사드립니다.
