### ISSUE TITLE
MSW 도입계획은 없으신가요

### ISSUE THREAD

**Issue by nadeda** [eGovFramework/egovframe-msa-edu#5]
Backend 없이 Frontend만 구동시켜서 테스트 하고싶을때 가장 보편적인게 msw인데 도입이 안되어 있어서요 아니면 따로 mock할 수 있는 방법이 있을까요?

**Comment by overpassion** [comment]
MSW를 사용하여 Mock처리 하는 것에 대해 가이드 하는 것은 아직 없습니다.
23년도에도 다른 일정으로 egovframe-msa-edu에서 계획은 아직 없는 상태 입니다.

**Comment by chris-yoon** [comment]
참여해 주셔서 감사드립니다.
