### ISSUE TITLE
[기능요구]: this is awesome repository I have ever seen

### ISSUE THREAD

**Issue by fizz12344321** [eGovFramework/egovframe-msa-edu#7]
### 연락처

G dragon

### 추가 요청 기능명

hoangnamtien9080@gmail.com

### 기능 상세 설명

well, I really appreciate this repository
To be honest, Why dont you use Keycloak for authentication and authorization in Microservices, it is suitable in this repo
2. Does it need to use Webflux, well, if you use it, you must use R2DBC or similar libraries to connect DB by Reactive Non blocking IO, right
3. Do you have any description files which are described about Architecture of this repo
4. Can you give me your contact to discuss more about it, or I can discuss in this link. Well, I dont know Korean language

**Comment by chris-yoon** [comment]
### Keycloak

We appreciate your feedback and suggestion about Keycloak.
We'll actively look into it to see if it can be incorporated into the next version.

### R2DBC

R2DBC is already applied in this repo.

### Description files

We'll be providing a description of repos in the near future.

### Contact to discuss more

You can email us at egovframesupport@gmail.com.

**Comment by chris-yoon** [comment]
### Webflux is suitable for your repo?

- Yes, you're right, webflux may not be a good fit for this repository, but we've included it to illustrate how to do reactive programming for educational purposes.

### Batch doesn't support Reactive Programming

- Using Spring Cloud Stream is another option to consider when implementing Reactive Programming with big sized data. By using Spring Cloud Stream, you can leverage its reactive programming model to handle large volumes of data in a highly scalable and efficient manner. You can also integrate Spring Batch with Spring Cloud Stream to enable processing of data in real-time as it is received from the messaging system.
